### ISSUE TITLE
Text hard to read.

### ISSUE THREAD

**Issue by skyguy6153** [AstrayDev/FCC-survey#2]
Great job on your first project! Some issues I had was the text is hard to read due to the light color of your background image. Adding linear-gradient to it should help with that though. 
- To do that, add the body selector in the CSS file and put this in:

body {  
background-image: 
    linear-gradient(
      rgba(0, 0, 0, 0.5),
      rgba(0, 0, 0, 0.5)
    ), url(https://www.canr.msu.edu/contentAsset/image/a60971f6-ccbb-4a7b-9c23-417a0ad19286/fileAsset/filter/Resize,Jpeg/resize_w/750/jpeg_q/80);
    background-size: contain;
}

- Added "linear-gradient" selector and rgba values for so text would be more visible.
-Used google image's "search by image" option to find your cheese picture. I then right clicked  the image and selected copy image address. I pasted that into the url value in the body element that way the image didn't need to be downloaded to my PC.

**Comment by AstrayDev** [comment]
Thanks! I'll try it next time I get the chance. CSS is definitely giving me
more trouble than html so far, just a lot of different features that are
hard for me to understand and utilize properly.

**Comment by AstrayDev** [comment]
I hope this looks better. I uploaded the new files but they are new files now, separate from the FCC-survey folder. However since I feel like I almost messed something up real bad I'm leaving it as is.

**Comment by skyguy6153** [comment]
Yes, much easier to read the words when you input your image into the image.  The linear linear-gradient rgba() values could be a tad lighter (like `rgba(0, 0, 0, 0.6)` would be just right).

![Sample1](https://user-images.githubusercontent.com/53711550/221383924-79b2d843-2bc8-4ae7-aaf5-f91f6d1d78b9.JPG)

**Comment by AstrayDev** [comment]
Happy that it's mostly better. I agree maybe it's a bit harsh but heh by that point it's mostly just changing number a bit and it's not like I'm hosting it online aside from this repo. Plus the reason the cheese.jpg is there is cause I edited it on paint to fit better, so that it wouldn't either repeat or just fill a small space. Though it became a bit stretched because of it. There's probably a better way to do that but that's what I did for this one. But thanks for the advice thus far!
